### ISSUE TITLE
Bukan down tapi baseurl belum diganti

### ISSUE THREAD

**Issue by binsarjr** [bagussatoto/Evoting-Client#6]
[Cek disini](https://github.com/bagussatoto/Evoting-Client-AMIKOM/blob/main/src/API/http.js#L3)

**Comment by bagussatoto** [comment]
Sebenarnya yang membuat ada proses server down

[Cek Ini Aja](https://github.com/bagussatoto/Evoting-Client-AMIKOM/blob/c21a1d448528727f83c1445221fe69675a3e2bb3/src/components/Loader.vue#L21)

Terima kasih berkunjung bang @binsarjr 🙏🏽
